#!/usr/bin/python3
import os
import sys
import pandas as pd
filename=str(sys.argv[1])

data = pd.read_excel('./'+filename,engine='openpyxl');
data.to_json(filename.split('.')[0]+'.json',orient='records');




